spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:nexfit}
      auto-index-creation: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

aws:
  s3:
    prefix: ${AWS_S3_PREFIX:prod}

launchdarkly:
  enabled: ${LAUNCHDARKLY_ENABLED:true}

media:
  sync:
    on-startup: ${MEDIA_SYNC_ON_STARTUP:false}
